const wordList = {
  "apple": true,
  "banana": true,
  "cherry": true,
  "date": true,
  "elderberry": true,
  "fig": true,
  "grape": true,
  "honeydew": true,
  "kiwi": true,
  "lemon": true,
  "mango": true,
  "orange": true,
  "pear": true,
  "quince": true,
  "raspberry": true,
  "strawberry": true,
  "tangerine": true,
  "ugli": true,
  "watermelon": true,
};
